catalog/urls.py
from django.urls import path
from . import views

app_name = 'catalog'

urlpatterns = [
    path('', views.index, name='index'),

    # Books
    path('books/', views.BookListView.as_view(), name='book_list'),
    path('book/<int:pk>/', views.BookDetailView.as_view(), name='book_detail'),
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book_update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book_delete'),
    # Authors
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('author/<int:pk>/', views.AuthorDetailView.as_view(), name='author_detail'),
    path('my_books/', views.LoanedBooksByUserListView.as_view(), name='my_books'),
    path('author_detail/<int:pk>', views.AuthorDetailView.as_view(), name='author_detail'),

    path('author/create/', views.AuthorCreate.as_view(), name='author_create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author_update'),
    path('author/<int:pk>/delete/', views.author_delete, name='author_delete'),
    path('book/<uuid:pk>/loan/', views.loan_book_librarian, name='loan_book_librarian'),
    path('available/', views.AvailBooksListView.as_view(), name='all_available'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':
settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':
settings.STATIC_ROOT}),
    path('', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from django.conf import settings
class Genre(models.Model):
    """Model representing a book genre."""
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction)')
    def __str__(self):
        """String for representing the Model object."""
        return self.name
class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('Died', null=True, blank=True)
    author_image = models.ImageField(upload_to='images/', null=True, blank=True)
    class Meta:
        ordering = ['last_name', 'first_name']
    def get_absolute_url(self):
        """Returns the URL to access a particular author instance."""
        return reverse('catalog:author_detail', args=[str(self.id)])
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'
class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    # Foreign Key used because book can only have one author, but authors can have multiple books
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.CharField('ISBN', max_length=13, unique=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')
    book_image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.title
    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('catalog:book_detail', args=[str(self.id)])
class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date
        and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ['due_back']
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'

catalog/forms.py
from .models import BookInstance
from django import forms

class LoanBookForm(forms.ModelForm):
    """Form for a librarian to loan books."""
    # Disable the book field to prevent user from entering a book
    # book_title is for display purposes only - set required=False
    book_title = forms.CharField(disabled=True, required=False)

    class Meta:
        # display only the book title and the borrower to the librarian
        model = BookInstance
        fields = ('book_title','borrower',)

catalog/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book, Genre
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import datetime
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from .forms import LoanBookForm
from .models import Book, Author, BookInstance, Genre


@login_required
def index(request):
    num_books = Book.objects.count()
    num_instances = BookInstance.objects.count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_authors': num_authors,
        'num_visits': num_visits,
    }

    # If your index template is at: catalog/templates/catalog/index.html
    return render(request, 'catalog/index.html', context)


class BookListView(LoginRequiredMixin, generic.ListView):
    model = Book


class BookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Book


class AuthorListView(LoginRequiredMixin, generic.ListView):
    model = Author


class AuthorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Author


class AuthorCreate(LoginRequiredMixin, CreateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'author_image']

    def form_valid(self, form):
        author = form.save()
        return HttpResponseRedirect(reverse('catalog:author_list'))


class AuthorUpdate(LoginRequiredMixin, UpdateView):
    model = Author
    fields = ['first_name', 'last_name', 'date_of_birth', 'date_of_death', 'author_image']

    def form_valid(self, form):
        author = form.save()
        return HttpResponseRedirect(reverse('catalog:author_list'))


def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")  # /accounts/login/
    else:
        form = UserCreationForm()

    return render(request, "registration/register.html", {"form": form})


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Books on loan to the current user."""
    model = BookInstance
    template_name = 'catalog/my_books.html'
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects
            .filter(borrower=self.request.user, status__exact='o')
            .order_by('due_back')
        )


def author_delete(request, pk):
    author = get_object_or_404(Author, pk=pk)
    try:
        author.delete()
        messages.success(request, f"{author.first_name} {author.last_name} has been deleted")
    except Exception:
        messages.success(
            request,
            f"{author.first_name} {author.last_name} cannot be deleted. Books exist for this author"
        )
    return redirect('catalog:author_list')


class AvailBooksListView(LoginRequiredMixin, generic.ListView):
    """List all available BookInstances."""
    model = BookInstance
    template_name = 'catalog/bookinstance_list_available.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(status__exact='a').order_by('book__title')


def loan_book_librarian(request, pk):
    """Loan a specific BookInstance by librarian."""
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        form = LoanBookForm(request.POST, instance=book_instance)
        if form.is_valid():
            book_instance = form.save(commit=False)
            book_instance.due_back = datetime.date.today() + datetime.timedelta(weeks=4)
            book_instance.status = 'o'
            book_instance.save()
            return HttpResponseRedirect(reverse('catalog:all_available'))
    else:
        form = LoanBookForm(
            instance=book_instance,
            initial={'book_title': book_instance.book.title if book_instance.book else ''}
        )

    return render(request, 'catalog/loan_book_librarian.html', {'form': form})

class SuperuserRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser
class BookCreate(LoginRequiredMixin, SuperuserRequiredMixin, CreateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'book_image']

    def form_valid(self, form):
        post = form.save(commit=False)
        post.save()


        for genre in form.cleaned_data['genre']:
            theGenre = get_object_or_404(Genre, name=genre)
            post.genre.add(theGenre)

        post.save()
        return HttpResponseRedirect(reverse('catalog:book_list'))

class BookUpdate(LoginRequiredMixin, SuperuserRequiredMixin, UpdateView):
    model = Book
    fields = ['title', 'author', 'summary', 'isbn', 'genre', 'book_image']
    template_name = 'catalog/book_form.html'

    def form_valid(self, form):
        post = form.save(commit=False)


        for genre in post.genre.all():
            post.genre.remove(genre)

        post.save()


        for genre in form.cleaned_data['genre']:
            theGenre = get_object_or_404(Genre, name=genre)
            post.genre.add(theGenre)

        post.save()
        return HttpResponseRedirect(reverse('catalog:book_list'))

def book_delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    try:
        book.delete()
        messages.success(request, f"{book.title} has been deleted")
    except:
        messages.success(request, f"{book.title} cannot be deleted")
    return redirect('catalog:book_list')

class BookDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Book
    template_name = "catalog/book_confirm_delete.html"
    success_url = reverse_lazy("catalog:book_list")

    def test_func(self):
        return self.request.user.is_superuser

catalog/templates/catalog/author_delete.html
{% extends "catalog/base.html" %}

{% block content %}
    {% if perms.catalog.delete_author %}
        <h1>Delete Author {{ author.first_name }}</h1>
        <form method="Post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger" value="Delete">
            <a href="{% url 'catalog:index' pk=author.id %}">Cancel</a>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'catalog:index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "catalog/base.html" %}

{% block content %}
  <h1>Name: {{ author.first_name }} {{ author.last_name }}</h1>

  <p><strong>Date of Birth:</strong> {{ author.date_of_birth|default_if_none:"" }}</p>
  <p><strong>Date of Death:</strong> {{ author.date_of_death|default_if_none:"" }}</p>

  {% if author.author_image %}
    <p>
      <img
        alt="Author image"
        src="{{ author.author_image.url }}"
        style="max-width: 200px; height: auto;"
      />
    </p>
  {% endif %}

  <h4>Books by this author</h4>
  {% if author.book_set.all %}
    <ul>
      {% for book in author.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No Books Available</p>
  {% endif %}

  <p>
    <a class="btn btn-secondary" href="{% url 'catalog:author_list' %}">Back to Authors</a>
  </p>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.catalog.create_author or perms.catalog.edit_author %}
        <form action="" method="POST"> enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'catalog:index' %}">Home</a>
    {% endif %}
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <h1>Author List</h1>

    {% if user.is_superuser %}
        <p>
            <a class="btn btn-success" href="{% url 'catalog:author_create' %}">Add Author</a>
        </p>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible fade show"
role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    {% if author_list %}
        <table class="table table-bordered">
            {% for author in author_list %}
                <tr class="table-secondary">
                    <td><a href="{{ author.get_absolute_url }}">{{
author.first_name }} {{ author.last_name }}</a></td>

                    {% if user.is_superuser %}
                        {% if author.book_set.all %}
                            <td>Books Exist - Cannot delete author</td>
                        {% else %}
                            <td><a href="{% url 'catalog:author_delete'
pk=author.pk %}"
                                onclick="return confirm('Are you sure you want to delete?')"
                                class="btn btn-danger">Delete</a>
                            </td>
                        {% endif %}
                        <td><a href="{% url 'catalog:author_update' pk=author.pk %}" class="btn btn-primary">Edit Author</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p>There are no authors in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Local Library{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="{% static 'css/my_style.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'catalog:index' %}">Local Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:book_list' %}">All Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'catalog:author_list' %}">All Authors</a>
                </li>
                {% if user.is_authenticated %}
                    <li><a class="nav-link" href="{% url 'catalog:my_books' %}">My Books</a></li>
                     {% if user.is_superuser %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button"  data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Librarian Functions
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'catalog:author_create' %}">Add Author</a></li>
                                <li><a class="dropdown-item" href="{% url 'catalog:book_create' %}">Add Book</a></li>
                                <li><a class="dropdown-item" href="{% url 'catalog:all_available' %}">View Available Books</a></li>
                            </ul>
                        </li>
                    {% endif %}
                {% endif %}
            </ul>
        </div>
    <ul class="nav navbar-nav ml-auto">
        {% if user.is_authenticated %}
            <li>
                <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">Log out</button>
                </form>
            </li>
        {% else %}
            <li><a class="nav-link" href="{% url 'login' %}"><span
    class="glyphicon glyphicon-log-in"></span>Login</a>
            </li>
            <li><a class="nav-link" href="{% url 'register' %}"><span
    class="glyphicon glyphicon-log-in"></span>Sign Up</a>
            </li>
        {% endif %}
    </ul>
    </div>
</nav>
<div class="container">
    {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
    {% endif %}
</div>
<div class="container">
    <br/>
    {% block content %}

    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>

catalog/templates/catalog/book_confirm_delete.html
{% extends "catalog/base.html" %}

{% block content %}
  <h1>Delete Book</h1>

  <p>Are you sure you want to delete: <strong>{{ object.title }}</strong>?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, delete</button>
    <a class="btn btn-secondary" href="{% url 'catalog:book_detail' object.pk %}">Cancel</a>
  </form>
{% endblock %}

catalog/templates/catalog/book_delete.html
{% extends "catalog/base.html" %}
{% block content %}
{% if user.is_superuser %}
<h1>Delete Book: {{ book.title }}</h1>
<form method="POST">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a class="btn btn-secondary" href="{% url 'catalog:book_list' %}">Cancel</a>
</form>
{% else %}
<p>You do not have permission to access this feature</p>
<a href="{% url 'catalog:index' %}">Home</a>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "catalog/base.html" %}
{% block content %}

    {% if book.book_image %}
        <p>
        <img src="{{ book.book_image.url }}" alt="{{ book.title }}" style="max-width:300px; height:auto;">
        </p>
    {% endif %}
    <h1>Title: {{ book.title }}</h1>




    <p><strong>Author:</strong><a href="{% url 'catalog:author_detail' book.author.id %}">{{ book.author }}</a></p>
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all|join:", " }}</p>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}"> {{ copy.get_status_display }}</p>
            {% if copy.status != 'a' %}
                <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
            {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
         {% endfor %}
        </div>
{% endblock %}

<p>
  <a class="btn btn-secondary" href="{% url 'catalog:book_list' %}">Back to Books</a>
</p>

catalog/templates/catalog/book_form.html
{% extends "catalog/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
{% if user.is_superuser %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Submit" class="btn btn-primary"/>
</form>
{% else %}
<p>You do not have permission to access this feature</p>
<a href="{% url 'catalog:index' %}">Home</a>
{% endif %}
{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "catalog/base.html" %}
{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})</li>
                <a class="btn btn-danger btn-sm"
                    href="{% url 'catalog:book_delete' pk=book.pk %}">
                    Delete
                </a>
            {% if user.is_superuser %}
                <a class="btn btn-primary btn-sm" href="{% url 'catalog:book_update' pk=book.pk %}">Edit Book</a>
            {% endif %}
            {% if book.book_image %}
                <img src="{{ book.book_image.url }}" alt="{{ book.title }}" style="height:60px; width:auto;">
            {% endif %}
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_available.html
{% extends "catalog/base.html" %}

{% block content %}
  {% if perms.catalog.edit_bookinstance %}
    <h1>All Available Books</h1>

    {% if bookinstance_list %}
      <table class="table table-bordered">
        {% for bookinst in bookinstance_list %}
          <tr class="table-secondary">
            <td>
              <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">
                {{ bookinst.book.title }}
              </a>
            </td>
            <td>
              <a href="{% url 'catalog:loan_book_librarian' bookinst.id %}">
                Loan
              </a>
            </td>
          </tr>
        {% endfor %}
      </table>
    {% else %}
      <p>There are no books available.</p>
    {% endif %}

  {% else %}
    <p>You do not have authorization to view this feature</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}

{% block content %}
    <h1>Local Library Home</h1>
    <p>The library has the following books and authors:</p>
    <ul>
        <li><strong>Books:</strong> {{ num_books }}</li>
        <li><strong>Copies:</strong> {{ num_instances }}</li>
        <li><strong>Copies available:</strong> {{num_instances_available }}</li>
        <li><strong>Authors:</strong> {{ num_authors }}</li>
    </ul>
        <p>You have visited this page {{ num_visits }} time{{ num_visits|pluralize }}.</p>
{% endblock %}

catalog/templates/catalog/loan_book_librarian.html
{% extends "catalog/base.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>

{% endblock %}

catalog/templates/catalog/my_books.html
<!DOCTYPE html>
<html lang="en">
{% extends "catalog/base.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>
        {% for bookinst in bookinstance_list %}
        <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
            <a href="{% url 'catalog:book_detail' bookinst.book.pk %}">{{
            bookinst.book.title }}</a> ({{ bookinst.due_back }})
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}
</html>